source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SAStickyHeaderView_Example', :exclusive => true do
  pod "SAStickyHeaderView", :path => "../"
end

target 'SAStickyHeaderView_Tests', :exclusive => true do
  pod "SAStickyHeaderView", :path => "../"

  pod 'FBSnapshotTestCase'
end
